channels:
- conda-forge
dependencies:
- python=3.12.12
- pip<=25.3
- pip:
  - mlflow==3.6.0
  - cloudpickle==3.1.2
  - numpy==1.26.4
  - pandas==2.1.4
  - psutil==7.0.0
  - pyarrow==22.0.0
  - scikit-learn==1.7.2
  - scipy==1.16.3
  - xgboost==3.1.1
name: mlflow-env
